version: '3.0'

services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "8282:80/tcp"
    environment:
      TZ: 'America/Mexico_City'
    # Volumes store your data between container upgrades
    volumes:
      - '/mnt/hdd/data_services/wallos/db:/var/www/html/db'
      - '/mnt/hdd/data_services/wallos/logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped

