services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
      #network_mode: bridge
    ports:
      # These ports are in format <host-port>:<container-port>
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    env_file: ".env"
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: ${DB_MYSQL_HOST}
      DB_MYSQL_PORT: ${DB_MYSQL_PORT}
      DB_MYSQL_USER: ${DB_MYSQL_USER}
      DB_MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${DB_MYSQL_NAME}
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
        - /mnt/hdd/data_services/nginx-proxy/data:/data
        - /mnt/hdd/data_services/nginx-proxy/letsencrypt:/etc/letsencrypt
