
services:
    filebrowser:
        image: 'filebrowser/filebrowser:s6'
        container_name: filebrowser
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/America/Mexico_City
        ports:
            - '8484:80'
        volumes:
            - '/:/srv'
            - '/mnt/hdd/data_services/filebrowser/database/filebrowser.db:/database/filebrowser.db'
            - '/mnt/hdd/data_services/filebrowser/config/.filebrowser.json:/config/.filebrowser.json'
