
version: '3.3'
services:
    filebrowser:
        volumes:
            - '/:/srv'
            - '/mnt/hdd/data_services/filebrowser/filebrowser.db:/database/filebrowser.db'
            - '/mnt/hdd/data_services/filebrowser/settings.json:/config/settings.json'
        environment:
            - PUID=$(id
            - PGID=$(id
        ports:
            - '8484:80'
        image: 'filebrowser/filebrowser:s6'
