version: '3.5'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - /path/to/config:/config
      - /path/to/cache:/cache
      - type: bind
        source: /mnt/hdd/media
        target: /media
      - type: bind
        source: /mnt/hdd/media
        target: /media
        read_only: true
    ports:
      - 8096:8096
    restart: 'unless-stopped'
