version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      #"- ./uptime-kuma-data:/app/data
      - /mnt/hdd/data_services/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
